server:
  port: 10010
spring:
  application:
    name: leyou-geteway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
           defaultZone: http://localhost:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/**
